# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\loginForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.setWindowModality(QtCore.Qt.NonModal)
        loginWindow.setEnabled(True)
        loginWindow.resize(400, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(loginWindow.sizePolicy().hasHeightForWidth())
        loginWindow.setSizePolicy(sizePolicy)
        loginWindow.setMinimumSize(QtCore.QSize(400, 200))
        loginWindow.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        loginWindow.setFont(font)
        loginWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        loginWindow.setAcceptDrops(False)
        loginWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius: 20%;")
        self.verticalLayout = QtWidgets.QVBoxLayout(loginWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(loginWindow)
        self.widget_3.setStyleSheet("border-radius: 20%;\n"
"background-color: rgb(0, 170, 255);\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.widget_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("border: none;\n"
"color: rgb(65, 65, 65);\n"
"background-color: rgb(245, 245, 245);\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border: none;\n"
"color: rgb(65, 65, 65);\n"
"background-color: rgb(245, 245, 245);\n"
"")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.widget_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginButton = QtWidgets.QPushButton(self.frame_2)
        self.loginButton.setMinimumSize(QtCore.QSize(100, 40))
        self.loginButton.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setStyleSheet("border-radius: 10%;\n"
"font: 75 14pt \"Microsoft YaHei UI\";\n"
"font-weight: bold;\n"
"color: rgb(65, 65, 65);\n"
"background-color: rgb(245, 245, 245);\n"
"")
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout.addWidget(self.loginButton)
        self.exitButton = QtWidgets.QPushButton(self.frame_2)
        self.exitButton.setMinimumSize(QtCore.QSize(100, 40))
        self.exitButton.setMaximumSize(QtCore.QSize(100, 40))
        self.exitButton.setStyleSheet("border-radius: 10%;\n"
"font: 75 14pt \"Microsoft YaHei UI\";\n"
"font-weight: bold;\n"
"color: rgb(65, 65, 65);\n"
"background-color: rgb(245, 245, 245);")
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout.addWidget(self.exitButton)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.widget_3)

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "Login Form"))
        self.loginButton.setText(_translate("loginWindow", "LOGIN"))
        self.exitButton.setText(_translate("loginWindow", "EXIT"))
